### PR TITLE
Migrating to shared feathers-service-tests suite

### PR DESCRIPTION
**Pull request by daffl**
This uses the shared test suite at https://github.com/feathersjs/feathers-service-tests. It looks like two tests are failing. @ekryski or @marshallswain maybe you can have a look?

### CODE REVIEW

**Comment by daffl** [comment]
Specifically `$select` and `$not`. I think `$select` just has the wrong format (it is tested against an array now) and it looks like NeDB doesn't support `$not` (which is odd because it is in the documentation).

**Comment by ekryski** [comment]
I can take a look this afternoon most likely. I passed out early last night so I'll be hammering pretty hard on Feathers today. :sleeping:

**Comment by daffl** [comment]
Ok should be fixed now. I had to update the tests for `$not` and submit a PR for `feathers-knex`.

**Comment by daffl** [comment]
So the tests for `$not` were actually what `$ne` is supposed to do. This one should be good to go now except for the updated documentation that I am currently working on.

**Pull request merged**
